print "Enter the company name as used for pool and queue"
print "(ex. output.wellsfargo_enriched_pools)"
name = raw_input("output.")
print "\n\n Enter the formal company name"
print "(ex. Wells Fargo)"
forname = raw_input("name:")
print "\n\n Enter name of case"
print "(ex. Underwriter)"
case = raw_input("case:") 

print "\n\n----------insert data into enrichment queue----------"
print "insert into output." + name + "_enrichment_queue"
print "select profile_id"
print "from coredb.profile"
print "where profile_id not in (select profile_id from output." + name + "_enrichment_queue)"
print "  --and profile_id not in (select profile_id from output." + name + "_enrichment_queue_archive)"
print "  and rtrim(ltrim(title_freeform)) is not null"
print "\n\n----------insert data into enriched pools----------"
print "insert into output." + name + "_enriched_pools"
print "select '" + forname + "' as company,"
print "    'Admin Pool - " + case + "' as pool_name, profile_id"
print "from coredb.profile where rtrim(ltrim(title_freeform)) is not null"
print "\n\n----------insert enriched pools into archive----------"
print "insert into output." + name + "_enriched_pools_archive select * from"
print "output." + name + "_enriched_pools;"
print "\n\n----------insert enrichment queue into archive----------"
print "insert into output." + name + "_enrichment_queue_archive select * from"
print "output." + name + "_enrichment_queue;"
print "\n\n----------truncate enriched pools----------"
print "truncate output." + name + "_enriched_pools;"
print "\n\n----------truncate enrichment queue----------"
print "truncate output." + name + "_enrichment_queue;"
print "\n\n----------create enriched pools table----------"
print "CREATE TABLE source.output." + name + "_enriched_pools ("
print "    company varchar(10),"
print "    pool_name varchar(68),"
print "    profile_id int8"
print ");"
print "\n\n----------create enrichment queue table----------"
print "CREATE TABLE source.output." + name + "_enrichment_queue ("
print "    profile_id int8"
print ");"